name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        exampleDir:
          - click
          - deleteCookies
          - waitForDisplayed
          - waitUntil
          - keys
          - queryElements
          - overwriteCommand
          - selectors
          - getting-started
          - setup
          - component-testing
          - api/webdriver
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm ci
          env:
            DETECT_CHROMEDRIVER_VERSION: true
        - name: Test
          run: npm run ${{ matrix.exampleDir }}
          working-directory: ${{ matrix.exampleDir }}
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: ${{ matrix.exampleDir }}/logs